### ISSUE TITLE
How to set cloud role name?

### ISSUE THREAD

**Issue by Abhith** [nuxt-community/applicationinsights-module#19]
How to configure this module to have a cloud role name as mentioned here: https://github.com/microsoft/ApplicationInsights-JS#example-setting-cloud-role-name

Note: CMTY not listing ApplicationInsights module, that's why created here directly.

**Comment by aldarund** [comment]
You can do it in your plugin . e.g. create a plugin and get appInsights from context and set role like its described in your link
