### ISSUE TITLE
@nuxtjs/dotenv is not supported?

### ISSUE THREAD

**Issue by NewGyu** [nuxt-community/applicationinsights-module#20]
Hello. Thank you for this useful module. I have a question about this module with dotenv. This module does not support dotenv module?

My nuxt.config.js is below.
```
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/dotenv',
    '@nuxtjs/applicationinsights'
  ],
  dotenv: {
    filename: `config/.env.${process.env.ENV || 'DEV'}`
  },
```

And .env.DEV is below.
```
APPINSIGHTS_INSTRUMENTATION_KEY={{my_istrumentation_key}}
```

When `npm run`,
* ENV=DEV npm run build
* ENV=DEV npm run dev

The following message is displayed.

> ℹ Errors will not be logged because no instrumentationKey has been provided     

Then telemetry cannot be sent.

Note:
> IMPORTANT: Please use the following link to create a new issue:
> https://cmty.app/nuxt/issues/new?type=bug-report&repo=ApplicationInsights

Sorry, I cannot choose this applicationinsights-module. So I made this issue directly.

Thanks.

**Comment by ThunderDev1** [comment]
Did you set the key ? In your nuxt.config, you need the following:

`appInsights: {
    instrumentationKey: process.env.APPINSIGHTS_INSTRUMENTATION_KEY
},`

**Comment by NewGyu** [comment]
Thanks. I got the above means that:

* I have to set the key explicitly.
* This module doesn't read Environment Variables which are defined in `.env` file implicitly.
