### ISSUE TITLE
Support for nuxt 3 and nuxt-bridge

### ISSUE THREAD

**Issue by DerekAlanGilbert** [nuxt-community/applicationinsights-module#45]
Deconstructing $appInsights from asyncData no longer works. An empty object is returned while running on nuxt-bridge.

**Comment by nathanlentz** [comment]
Bumping this - Nuxt 3 has been in RC for a while now, it would be nice to get this working.

**Comment by thijsw** [comment]
Bumping again now that 3.0.0 is stable

**Comment by Leapfrognz** [comment]
Can we have an ETA on Nuxt 3 support?

**Comment by doubleujay** [comment]
Any updates on this? Would love to see support for v3. Thanks!

**Comment by harlan-zw** [comment]
Will track Nuxt 3 support here: https://github.com/nuxt-community/applicationinsights-module/issues/45

If anyone is interested in helping migrate the module, please let us know in this issue :)
